import type { Calling } from "./callings"

export const beatTypes = ["minor", "major", "zenith"] as const
export type BeatType = (typeof beatTypes)[number]

export type Beat = {
    type: BeatType
    description: string
}

const beat = (type: BeatType, description: string): Beat => ({ type, description })

export const beatsByCalling: Record<Calling, Beat[]> = {
    Adventure: [
        beat("minor", "Charm someone with tales of your exploits."),
        beat("minor", "Engage in reckless abandon with drink, drugs or sex."),
        beat("minor", "Slay a beast that drops resources of D10 or higher."),
        beat("minor", "Access a haven in Tier 2 of the Heart."),
        beat("minor", "Take Major Blood fallout."),
        beat("minor", "Take Major Fortune fallout."),
        beat("minor", "Defeat a powerful foe one-on-one."),
        beat("minor", "Help an important or influential figure in a haven."),
        beat("minor", "Refuse to back down when it would be beneficial to do so."),
        beat("minor", "Establish a connection."),
        beat("minor", "Get in trouble with the Hounds."),
        beat("minor", "Rescue someone from peril."),
        beat("minor", "Make a dramatic entrance that's a Risky action."),
        beat("minor", "Claim a resource of at least D10 from a dangerous location."),
        beat("minor", "Defend a haven from attack."),
        beat("minor", "Have at least three havens know your name, for good or ill."),
        beat("minor", "Rush into danger before anyone else."),
        beat("minor", "Have a cocktail, fighting move or legendary beast named after you."),
        beat("minor", "Go somewhere where no one else has stepped foot for at least a century."),
        beat("minor", "Win an unarmed brawl in a haven."),
        beat("minor", "Kick someone off a tall structure (they really deserved it)."),
        beat("major", "Acquire a rare or powerful D12 value item, preferably magic."),
        beat("major", "Slay a beast that's at least five times your size."),
        beat("major", "Have a landmark or connection named after you."),
        beat("major", "Upgrade a haunt to D12."),
        beat("major", "Save a haven from destruction or doom."),
        beat("major", "Connect three havens to one another with permanent paths."),
        beat("major", "Successfully perform a Dangerous action that saves the day."),
        beat("major", "Catalogue your exploits for an extended period, either yourself or through a hired bard."),
        beat("major", "Lead a group or organisation other than your delving party."),
        beat("major", "Successfully lead, and take full credit for, a delve that takes you to Tier 3 or deeper."),
        beat("zenith", "Reach Tier 4 of the Heart."),
        beat("zenith", "Lead a haven to prosperity."),
    ],
    Enlightenment: [
        beat("minor", "Allude to the events that led you to seek forbidden knowledge to achieve an impossible task."),
        beat("minor", "Put the acquisition of knowledge above preserving the lives of your allies."),
        beat("minor", "Gain access to knowledge that someone tried to conceal."),
        beat("minor", "Gain favour with a faction that can help you learn more about your goal."),
        beat("minor", "Take Minor Mind fallout."),
        beat("minor", "Destroy evidence or rhetoric that proves your task to be impossible."),
        beat("minor", "Sell or sacrifice a D8 or higher resource to secure a secret."),
        beat("minor", "Reach a landmark on Tier 3 of the Heart."),
        beat("minor", "Find a helpful text."),
        beat("minor", "Succeed at a task that someone else has recently failed to achieve."),
        beat("minor", "Mark D8 stress to an NPC bond and describe what happens."),
        beat("minor", "Acquire an NPC bond who has access to useful information."),
        beat("minor", "Establish a connection on a delve."),
        beat("minor", "Take Minor Supplies fallout."),
        beat("minor", "Flee from combat or a similarly dangerous situation, or hide until it all blows over."),
        beat("minor", "Release your shocking findings in a journal published in the City Above."),
        beat("minor", "Meet someone from your old life who's trying to get you to give up on your quest."),
        beat("minor", "Dissect something or interrogate someone that can shed light on your task."),
        beat("minor", "Buy some cutting-edge, experimental or finely-made equipment and use it on a delve."),
        beat("major", "Take Major Mind fallout."),
        beat("major", "Kill someone who is trying to stop you from claiming knowledge."),
        beat("major", "Sell or sacrifice a D12 resource to secure a secret."),
        beat("major", "Destroy a haunt to learn more about your task."),
        beat("major", "Gain authority within a faction that you can use to learn more about your goal."),
        beat("major", "Find a source of knowledge on Tier 3 of the Heart."),
        beat("major", "Take Major Supplies fallout."),
        beat("major", "Acquire a renowned piece of equipment."),
        beat("major", "Attract a protege who's read your work and is determined to learn more."),
        beat("major", "Explore a mysterious tower whilst on a delve, increasing the delve's difficulty by D12."),
        beat("zenith", "Find the final secret you have so desperately sought and use it to solve your impossible task."),
        beat("zenith", "Find the final secret you have so desperately sought and destroy it so no one else can know of it."),
    ],
    Forced: [
        beat("minor", "Receive orders from your masters."),
        beat("minor", "Follow orders from your masters, even though they put you at risk."),
        beat("minor", "Rebel against your orders, even though this puts you at risk."),
        beat("minor", "Forge a friendship or romantic relationship with an NPC."),
        beat("minor", "Get into trouble as someone discovers your chequered past."),
        beat("minor", "Betray someone because of your true nature."),
        beat("minor", "Take Minor Fortune fallout."),
        beat("minor", "Do something dangerous to conceal your past."),
        beat("minor", "Invoke your masters' name to get what you want."),
        beat("minor", "As a result of using Collateral, an NPC is taken out of action or a PC suffers fallout."),
        beat("minor", "Find a sanctuary where your masters cannot reach you."),
        beat("minor", "Rescue an NPC from trouble that you caused."),
        beat("minor", "Receive a time-critical mission that leads you away from your other objectives."),
        beat("minor", "Receive aid from someone reprehensible who's in the employ of your master."),
        beat("minor", "Send a requested D8 or higher resource back to your master rather than using it yourself."),
        beat("minor", "Perform a seemingly unconnected action for your masters that has grim consequences."),
        beat("minor", "Cover up a crime that someone else committed on behalf of your masters."),
        beat("minor", "Claim you're doing something on behalf of your masters when in fact it's for your own ends."),
        beat("minor", "Involve an NPC in your master's schemes."),
        beat("minor", "Do a favour for someone to gain leverage over them."),
        beat("major", "Destroy something important to your masters."),
        beat("major", "Learn or possess something that lessens the control your masters have over you."),
        beat("major", "Perform a truly reprehensible act on behalf of your masters."),
        beat("major", "Suffer the consequences of refusing to perform an important act on behalf of your masters."),
        beat("major", "Take Major Fortune fallout."),
        beat("major", "An important or beloved NPC dies after you bring them into your master's schemes."),
        beat("major", "Thanks to your actions, a haven is pitched into deadly chaos."),
        beat("major", "Coerce an important or beloved NPC into undertaking a task they don't want to do."),
        beat("major", "Aid another person, who you know and hate, that is also in the employ of your masters."),
        beat("major", "Complete a major objective for your master, something taking at least two sessions to achieve."),
        beat("zenith", "End the control your master has over you."),
        beat("zenith", "Take bloody revenge on your master."),
    ],
    Heartsong: [
        beat("minor", "Following a long ritual, name The Heart. Only refer to it by this name from now on."),
        beat("minor", "Take Minor Echo fallout."),
        beat("minor", "See something from your dreams in the real world."),
        beat("minor", "Consume something of the Heart, such as the flesh of a heartsblood beast."),
        beat("minor", "Be rendered helpless in the Heart for an hour or more."),
        beat("minor", "Perform a rite at a place of power on Tier 2 or deeper."),
        beat("minor", "Damage or sabotage a haven, letting the Heart in."),
        beat("minor", "Sacrifice something you love to the Heart."),
        beat("minor", "Allow something dangerous of the Heart to live when you could have killed it."),
        beat("minor", "Let your curiosity lead you into danger."),
        beat("minor", "Undergo a trance-like vision that lasts for hours."),
        beat("minor", "Communicate with something of the Heart."),
        beat("minor", "Witness an emissary of the Heart Itself."),
        beat("minor", "Experience a pulse, the changing of the Heart from one state to another, first-hand."),
        beat("minor", "Receive insight from a witch, a heartsblooded person or something stranger still."),
        beat("minor", "Gain information on why you have been chosen by the Heart."),
        beat("minor", "Receive a strange surgical implant or heartsblood transfusion."),
        beat("minor", "Build a shrine to the Heart somewhere important."),
        beat("minor", "Terrify or intrigue an NPC with your obsession."),
        beat("minor", "Perform an act of service to an NPC witch."),
        beat("minor", "Shelter someone touched by the Heart from persecution."),
        beat("minor", "Find a heart-touched sapling on a delve and bring it back to a haven for planting."),
        beat("minor", "Convince the party to collect Cursed resources on a delve, adding D6 to the delve's resistance."),
        beat("major", "Take Major Echo fallout."),
        beat("major", "Perform a rite at a place of power on Tier 3 or deeper."),
        beat("major", "Sacrifice someone important to the Heart."),
        beat("major", "Establish a bond with a hearts-blood beast on Tier 2 or deeper."),
        beat("major", "Show the truth of the Heart's majesty to an outsider on Tier 2 or deeper."),
        beat("major", "Meet and learn from an emissary of the Heart."),
        beat("major", "Destroy a haven, returning the land to the Heart."),
        beat("major", "One of your bonds takes Critical fallout thanks to your actions."),
        beat("major", "Deliver a crucial message on behalf of the Heart."),
        beat("major", "Visit three Vermissian Stations."),
        beat("zenith", "Become one with the Heart, and bind your essence to it."),
        beat("zenith", "Break the hold that the Heart has over you, ripping it from your body and spirit."),
    ],
    Penitent: [
        beat("minor", "Take Minor Blood fallout."),
        beat("minor", "Help someone vulnerable with no expectation of repayment."),
        beat("minor", "Repair something physical, such as a bridge, door or wall, that someone needs."),
        beat("minor", "De-escalate a situation that would have led to bloodshed."),
        beat("minor", "Spare someone's life."),
        beat("minor", "Make penance at a site that is important to your order."),
        beat("minor", "Punish an NPC for wrongdoing."),
        beat("minor", "Meet an NPC who hates you for what you've done."),
        beat("minor", "Perform an act in service to your order."),
        beat("minor", "Bring bodily harm to those who stand against your order."),
        beat("minor", "Sabotage the assets of those who stand against your order."),
        beat("minor", "Establish a connection to a landmark that's important to your order."),
        beat("minor", "Witness first-hand the tragic extent of your failings."),
        beat("minor", "Donate needed supplies to your order."),
        beat("minor", "Teach someone the value of your order's philosophies."),
        beat("minor", "Put yourself in great danger to protect your companions."),
        beat("minor", "Make reparations to an NPC that you have personally wronged."),
        beat("minor", "Do something your order would frown upon."),
        beat("minor", "Rescue or assist an NPC who belongs to your order."),
        beat("minor", "Openly attack the enemies of your order."),
        beat("minor", "Refuse a desirable offer due to the restrictions of your penance."),
        beat("major", "Take Major Blood fallout."),
        beat("major", "Convert an important NPC to your order's cause."),
        beat("major", "Establish continual connections between two landmarks on different tiers that are important to your order."),
        beat("major", "Perform an act that, if your order discovered it, would undo your penance."),
        beat("major", "Betray someone who really trusts you."),
        beat("major", "Save a landmark dedicated to your order."),
        beat("major", "Attack the enemies of your order when the odds are massively stacked against you."),
        beat("major", "Eliminate or completely undermine a faction that is opposed to your order."),
        beat("major", "Your order suffers a devastating setback, and you believe that it's your fault."),
        beat("major", "A member of your order begs you to perform an undesirable task; to refuse would be disgraceful."),
        beat("zenith", "Be truly absolved of your sins by a higher power."),
        beat("zenith", "Betray your order intentionally, this time."),
    ],
}
