import { type Resistance } from "./resistances"

export const falloutSeverities = ["minor", "major", "critical"] as const
export type FalloutSeverity = (typeof falloutSeverities)[number]

export type Fallout = {
    name: string
    description: string
    severity: FalloutSeverity
    resistance: Resistance
    effects: ("Immediate" | "Ongoing")[]
}

const fallout = <T extends Fallout>(fallout: T) => fallout

export const falloutOptions: Fallout[] = [
    fallout({
        name: "Battered",
        description: "Your dominant hand is hurt. Combat actions are Risky, and precise hand work is impossible for now.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Bleeding",
        description: "At the end of each situation while this remains, mark D4 Blood stress.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Disarmed",
        description: "You drop or lose what you were holding. Until you find a weapon, you only inflict D4 stress in combat.",
        severity: "minor",
        resistance: "blood",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Furious",
        description: "Pain makes you angry and suspicious. You cannot help another character by adding a die to their roll.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Limping",
        description: "You are slowed and exposed. You are first in line for ambushes, last when speed matters, and fast or quiet movement is Risky.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Ringing Head",
        description: "Your next action is Dangerous, the action after that is Risky, then your head clears and this fallout is removed.",
        severity: "minor",
        resistance: "blood",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Shattered",
        description: "Your armour is ruined and cannot provide Blood protection until repaired or replaced.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Spitting Teeth",
        description: "Speaking clearly or making a respectable impression is Risky.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Tired",
        description: "You are worn down and fraying. Skills no longer grant extra dice.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Winded",
        description: "Your melee attacks inflict stress at one die size lower than usual.",
        severity: "minor",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Clouded",
        description: "Your mind dulls itself for protection. Domains no longer grant extra dice.",
        severity: "minor",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Creepy",
        description: "You react in a disturbing way. Friendly witnesses mark D4 Mind stress.",
        severity: "minor",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Collateral Magic",
        description: "Your mind briefly reforms into a spell-pattern. You cast Aetheric Scourge on a nearby ally without paying its stress cost.",
        severity: "minor",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Fascination",
        description: "You become fixated on a strange subject. Pursuing it grants mastery; refusing a clear chance to investigate it costs D4 Mind stress.",
        severity: "minor",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Figment",
        description: "The GM gives you a Minor fallout from another resistance. You believe it is real and suffer its effects until this is removed.",
        severity: "minor",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Shaken",
        description: "Panic takes over. The GM chooses whether you fight, flee or freeze; remove this fallout at the end of the situation.",
        severity: "minor",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Take the Edge Off",
        description: "Until you reach intoxicants at a landmark and get insensible, roll twice for Mind stress and take the higher result.",
        severity: "minor",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Vulnerable",
        description: "You feel small and afraid. You cannot use Mind protection.",
        severity: "minor",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Weird",
        description: "You develop unsettling habits. At a bad moment, the GM may have your behavior sour a useful NPC against you.",
        severity: "minor",
        resistance: "mind",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Buboes",
        description: "Your skin blisters. Whenever you take Blood stress, also take D4 extra Blood stress.",
        severity: "minor",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Conduit",
        description: "The Heart's unreality flows through you. You cannot use Echo protection.",
        severity: "minor",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Deja Vu",
        description: "Pieces of your past appear in the Heart. The GM describes how reality echoes your memories.",
        severity: "minor",
        resistance: "echo",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Exodus",
        description: "You vomit up unnatural little creatures. Unprepared witnesses mark D4 Mind stress.",
        severity: "minor",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Follower",
        description: "A harmless but troublesome devotee decides you are chosen and begins trailing you from a distance.",
        severity: "minor",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Glitch",
        description: "You vanish and reappear only after every other player has acted at least once.",
        severity: "minor",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Hex-Eye",
        description:
            "Layered realities distort your sight. Distance-dependent actions are Risky, but once per session you may ask the GM what useful thing you see.",
        severity: "minor",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "The Ravening Call",
        description: "A broken mental howl lodges in you. It has no immediate effect, but can worsen into The Ravening Beast.",
        severity: "minor",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Strange Appetite",
        description: "You crave taboo or unnatural things. Next time you refresh Blood or Mind at a haunt, indulge the craving first or you cannot refresh.",
        severity: "minor",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Siren Song",
        description: "The GM names a nearby person or place. Anything except moving toward it or clearing your path is Risky until you reach it.",
        severity: "minor",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Broken",
        description: "An important item is damaged and unusable until you repair it with time and resources.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Collateral",
        description: "Next time you mark stress, a nearby ally marks the same amount, then this fallout is removed.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Foreboding",
        description: "Something bad is coming. The GM foreshadows a future danger; this can worsen into Crisis.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "The Hard Way",
        description: "You guide the party into danger. The next obstacle is Dangerous unless a solid plan reduces it.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "In Trouble",
        description: "You have angered an important person in this haven or a nearby one.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Long Way Round",
        description: "You arrive late. On a delve add D6 resistance; in a landmark you reach the target just in time for trouble.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Separated",
        description: "When you look back, your allies are gone. You must find them, or hope they find you.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Unlucky",
        description: "Things are about to worsen. You cannot use Fortune protection.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Word of Mouth",
        description: "Stories of your misdeeds spread ahead of you. Someone at your next destination plans to exploit that knowledge.",
        severity: "minor",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Shattered",
        description: "Your armour is ruined and cannot provide Blood protection until repaired or replaced.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Broken",
        description: "An important item is damaged and unusable until you repair it with time and resources.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Damaged",
        description: "One resource you carry is flawed or cracked; reduce its die size by one step.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Darkness",
        description: "Your spireblack oil runs low. Delve and Discern checks are Risky until someone spends D6 Supplies stress to help.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Debtor",
        description: "An NPC creditor calls in a favor during this session or the next.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Empty",
        description: "You are down to scraps and dregs. You cannot use Supplies protection.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Half Rations",
        description: "Food is scarce. When removing stress, roll twice and use the lower result; an ally can clear this by marking D6 Supplies stress.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Out of Ammo",
        description: "A ranged or powered weapon is out of ammunition and unusable until an ally with a similar weapon spends D6 Supplies stress.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Used Up",
        description: "Vital supplies are spoiled, stolen or spent. You cannot use healing items you own.",
        severity: "minor",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Arterial Wound",
        description: "A worse Bleeding result: mark D6 Blood stress at the end of every situation.",
        severity: "major",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Blinded",
        description: "You cannot see properly, perhaps permanently. Vision-based tasks are Dangerous.",
        severity: "major",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Broken Arm",
        description: "One arm is broken and unusable until healed, making some tasks Risky or Dangerous and others impossible.",
        severity: "major",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Broken Leg",
        description: "A leg is broken. Tasks that depend on it, including climbing or moving faster than a crawl, automatically fail.",
        severity: "major",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Critical Injury",
        description: "A vital injury costs you access to one skill chosen by the GM.",
        severity: "major",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Downed",
        description: "You are barely conscious and cannot move under your own power without medical attention.",
        severity: "major",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Exhausted",
        description: "Stop now or have someone carry you. You may take one final action, then collapse when it resolves.",
        severity: "major",
        resistance: "blood",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Aetheric Resonance",
        description: "As Collateral Magic, but Aetheric Scourge becomes a spell you permanently know and can cast at will.",
        severity: "major",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Addict",
        description: "You need intoxication to steady yourself. Sober Mind stress rolls twice and takes the higher; intoxication makes careful work Risky.",
        severity: "major",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Delusion",
        description: "The group and GM define a false belief you hold as true. Reality contradicts you next time the subject appears.",
        severity: "major",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Despair",
        description: "The GM chooses one domain you have access to; you lose access to it.",
        severity: "major",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Memory Holes",
        description: "The group and GM decide what awful thing you did and forgot. Everyone involved remembers except you.",
        severity: "major",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Phantasm",
        description: "As Figment, but the GM gives you a Major fallout from another resistance.",
        severity: "major",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Scarred",
        description: "As Shaken, and future encounters with the fallout source may require Endure or inflict D8 Mind stress.",
        severity: "major",
        resistance: "mind",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Unsettling",
        description: "As Shaken, and friendly witnesses to your disturbing behavior mark D6 Mind stress.",
        severity: "major",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Blooded",
        description: "Your body bears a Heart-touched mark. Whenever you mark Blood stress, roll twice and take the higher result.",
        severity: "major",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Cult",
        description: "Strange followers gather around you as a supposed scion of the Heart, complicating travel, havens and any attempt to exploit them.",
        severity: "major",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Dark Cravings",
        description: "As Strange Appetite, but the craving remains until this fallout is removed.",
        severity: "major",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Eyes",
        description:
            "Your eyes change or multiply. Darkness is no problem, but bright light hurts and may force Endure checks with stress on failure or partial success.",
        severity: "major",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "The Life Not Lived",
        description: "As Deja Vu, but you meet someone from your past who should be dead.",
        severity: "major",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Meat",
        description: "Mundane people feel hollow to you. Extended conversation may force Endure or D6 stress; intimacy can raise that to D10.",
        severity: "major",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Mirage",
        description: "The next landmark is a Heart-made copy built to tempt you. Remove this fallout once you realise it is fake.",
        severity: "major",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "The Ravening Beast",
        description: "The beast from your mind emerges and tries to consume you. Defeating it stops the scene, but this fallout can worsen further.",
        severity: "major",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Reconfigured Physiology",
        description: "Your organs and bones become wrong. You can no longer remove Blood stress or Blood fallout through haunts or medical kits.",
        severity: "major",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Vanished",
        description: "The next landmark you seek is gone; you find something else in its place.",
        severity: "major",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Crisis",
        description: "The danger hinted by Foreboding happens now.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Destroyed",
        description: "On a delve, erase an established connection; in a landmark, you ruin something valuable and remove a haunt if one exists.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Exiled",
        description: "You are barred from a current or nearby haven. Your allies may enter, but locals distrust them.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Grievance",
        description: "A faction, church, cult, haven, beast group or similar marks you as an enemy until you clear your name or force the issue.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Hell for Weather",
        description: "The area turns hostile or dangerously changes. Until you reach a landmark, all party actions are Risky.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Lost Map",
        description: "Your map is gone. Until replaced or recovered, you cannot use connections and all journeys count as unexplored.",
        severity: "major",
        resistance: "fortune",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Lost Property",
        description: "The GM chooses an item you misplaced. Retrieving it requires backtracking, assuming nobody took it first.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "No Way Out",
        description: "You lead the group into a dead end, trap or ambush. Remove this after you escape alive.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Reputation",
        description: "A rival delver comes to claim your head and supplies. Remove this after the ambush is over.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "The Road Less Travelled",
        description: "The next landmark is not the one expected, and is probably somewhere you hoped to avoid.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Unwilling Leader",
        description: "An unwanted group looks to you for solutions. They can be useful, but create more problems than they solve.",
        severity: "major",
        resistance: "fortune",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "In the Dark",
        description: "As Darkness, but something attacks while the light is gone; the fight is Dangerous until you regain light.",
        severity: "major",
        resistance: "supplies",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Lost Property",
        description: "The GM chooses an item you misplaced. Retrieving it requires backtracking, assuming nobody took it first.",
        severity: "major",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "No Rations",
        description: "As Half Rations, and all your actions are Risky from hunger. An ally can clear this by marking D8 Supplies stress.",
        severity: "major",
        resistance: "supplies",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Services Rendered",
        description: "Debt forces you into work you would rather avoid, either now or as a flashback. Refusing brings trouble.",
        severity: "major",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Sold",
        description: "You must sell something valuable to pay debts. If you have not used it since the last haven, it may already be gone.",
        severity: "major",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Spoiled",
        description: "A resource you carry is ruined, fake, broken or scattered. Remove it from your possessions.",
        severity: "major",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Bleeding Out",
        description: "You are dying. Choose one last useful act with mastery, or cling to life by sacrificing something vital.",
        severity: "critical",
        resistance: "blood",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Chosen",
        description: "The Heart returns you changed. Within a session or two, you transform into an Angel and retire from play.",
        severity: "critical",
        resistance: "blood",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "Ghost",
        description: "You die and haunt the party. Until laid to rest or destroyed, they mark D6 Mind or Echo stress at each session start.",
        severity: "critical",
        resistance: "blood",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Beast",
        description: "Your body becomes a monstrous Heart-thing. You vanish into legend and may return later as an adversary.",
        severity: "critical",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Burst",
        description: "Your body ruptures under what it contains. Nearby characters mark D6 Echo stress; your fate is death or worse.",
        severity: "critical",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Descent",
        description: "A landmark is dragged one tier deeper with you and anyone inside. You are swallowed by the Heart and retire.",
        severity: "critical",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Messiah",
        description: "Your cult forces a conclusion: you leave delving to lead them, or they reveal you as false and try to kill you.",
        severity: "critical",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Petrified",
        description: "Your body calcifies, ossifies or crystallises into a durable statue of yourself.",
        severity: "critical",
        resistance: "echo",
        effects: ["Ongoing"],
    }),
    fallout({
        name: "The Ravening",
        description: "A Ravening Beast tears itself out of you. You die, and nearby survivors must deal with the newborn monster.",
        severity: "critical",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Stranded",
        description: "You are lost in a fracture, parasite dimension or divergent future. Describe where you spend the rest of your life.",
        severity: "critical",
        resistance: "echo",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Abandon",
        description: "You lose yourself completely and wander into the wild. If you return, you are no longer recognisable.",
        severity: "critical",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Break",
        description: "You shatter. Loved ones nearby mark D8 Mind stress; disliked bystanders mark D8 Blood stress as you lash out, then you die or retire.",
        severity: "critical",
        resistance: "mind",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Obsessed",
        description: "Your purpose becomes cruel and consuming. Retire the character; they become an antagonist pursuing that goal.",
        severity: "critical",
        resistance: "mind",
        effects: ["Immediate", "Ongoing"],
    }),
    fallout({
        name: "Fool's Gold",
        description: "You seem to get exactly what you wanted, but it is false. The revelation breaks you and your story ends as a warning.",
        severity: "critical",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Heavy Hangs the Head",
        description: "You are made leader of a haven you cannot save. You get one useful act with its resources before everything collapses.",
        severity: "critical",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "A Slow and Insidious Killer",
        description: "Misplaced confidence catches up with you and grants you an ironic death.",
        severity: "critical",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Wrong Place",
        description: "You take a fatal blow meant for someone else. They are unharmed; you die.",
        severity: "critical",
        resistance: "fortune",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Defenceless",
        description: "Your protection fails at the worst moment and enemies leave you for dead.",
        severity: "critical",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Pitch Black",
        description: "In darkness, something drags you away and you do not return.",
        severity: "critical",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Plummet",
        description: "A rope, hook, line or hold gives way and you fall into the dark below.",
        severity: "critical",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
    fallout({
        name: "Starvation",
        description: "Hunger or dehydration overcomes you.",
        severity: "critical",
        resistance: "supplies",
        effects: ["Immediate"],
    }),
]
